"""Tâches du pipeline Prefect"""
from .ingestion import ingestion_task
from .profiling import profiling_task
from .parsing import parsing_task
from .mapping import mapping_task
from .cleaning import cleaning_task
from .typing import typing_task
from .standardization import standardization_task
from .dedup import dedup_task
from .validation import validation_task
from .enrichment import enrichment_task
from .mongodb_writer import mongodb_writer_task